### ISSUE TITLE
Did it show the word during the demo?

### ISSUE THREAD

**Issue by marksherman** [oplS16projects/Laura-Willis#5]
I believe I saw the word displayed, starting all in asterisks, and the letters guessed correctly, in the GUI during the demo. Current code release doesn't do that.
<img width="600" alt="screen shot 2016-05-05 at 8 08 42 pm" src="https://cloud.githubusercontent.com/assets/2035149/15060909/3963a5fc-12fd-11e6-8bca-1ef1d088e2bd.png">

**Comment by whand662** [comment]
It did, I'm not sure why it wouldnt show anything since that functionality
has been present for awhile. Both missing parts used procedure calls that
update the label text. These can be found in the game object, for
verification that the code is present.

Both laura and I updated to whatever the newest version of drracket was
about a month ago. It was tested on both of our computers and it was fully
functional. The release is exactly the same code we used in the
demonstration, no further work was done.

I hope that helps, let me know if I can be of any more help.
